### PR TITLE
initialize sheets client with credential from file or string

### LINKED ISSUE #22: Current code would not work on production
## environment information

- **Stage**:
local vs. production

## Description

As the config for local and production is a bit out of sync (#20) we canot deploy to production at the moment.

The properties contain `google.spreadsheet.credentials_path` and  the code has been adjusted to read the credentials from the file in order to make it run locally.
But on production it is using `google.spreadsheet.credentials` and directly putting the json in there.

So if we would deploy current code to production it would fail.

As a quick fix (while waiting for #20) we proposed to make the `GoogleSheetsApi` handle both properties (use the one that has a value).

### PR DESCRIPTION
**Pull request by erikpetzold**
closes #22

### CODE REVIEW

File: src/main/java/org/redischool/attendance/config/AppConfig.java [hunk 1]
```diff
@@ -12,4 +27,41 @@ public ObjectMapper objectMapper() {
...
+    public Sheets sheetsClientFromCredentials(@Value("${google.credentials}") String credentials) {
+        try {
+            InputStream resourceInputStream = new ByteArrayInputStream(credentials.getBytes());
+            GoogleCredential credential =
+                    GoogleCredential.fromStream(resourceInputStream).createScoped(SheetsScopes.all());
+
+            HttpTransport httpTransport = GoogleNetHttpTransport.newTrustedTransport();
+
+            return new Sheets.Builder(httpTransport, JacksonFactory.getDefaultInstance(), credential)
+                    .setApplicationName("Client for sheets-accessor").build();
```
Comment (jacekbilski) [inline src/main/java/org/redischool/attendance/config/AppConfig.java:41]: This part of code is common to both methods. I'd extract it.

**Review by jacekbilski — APPROVED** [review]
Besides this one little thing - LGTM.

**Review by Rappahannock — APPROVED** [review]
